//
//  AddBookView.swift
//  Bookworm
//
//  Created by Aaron Brown on 10/6/23.
//

import SwiftUI

struct AddBookView: View {
    //Property that enables saving data to the Managed Object Context. It holds the class that is generated by CoreData
    @Environment(\.managedObjectContext) private var moc
    @Environment(\.dismiss) private var dismiss
    
    @State private var author: String = ""
    @State private var genre: String  = "Fantasy"
    @State private var rating = 3
    @State private var review: String = ""
    @State private var title = ""
    
    private let genres: [String] = ["Fantasy", "Horror", "Kids", "Mystery", "Poetry", "Romance", "Thriller"]
    
    var body: some View {
        NavigationView {
            Form {
                Section {
                    TextField("Name of Book", text: $title)
                    TextField("Author's Name", text: $author)
                    
                    Picker("Genre", selection: $genre) {
                        ForEach(genres, id: \.self) {
                            Text($0)
                        }
                    }
                }
                Section {
                    TextEditor(text: $review)
                    RatingView(rating: $rating)
                } header: {
                    Text("Write a Review")
                }
                Section {
                    Button("Save") {
                        let newBook = Book(context: moc)
                        
                        newBook.id = UUID()
                        newBook.author = author
                        newBook.genre = genre
                        newBook.rating = Int16(rating)
                        newBook.review = review
                        newBook.title = title
                        
                        try? moc.save()
                        
                        dismiss()
                    }
                }
                .disabled(disableSave)
            }
            .navigationTitle("Add Book")
        }
    }
    
    var disableSave: Bool {
        if author.isEmpty || review.count < 5 || title.isEmpty {
            return true
        } else {
            return false
        }
    }
}

struct AddBookView_Previews: PreviewProvider {
    static var previews: some View {
        AddBookView()
    }
}
