//
//  ContentView.swift
//  Bookworm
//
//  Created by Aaron Brown on 10/5/23.
//

import SwiftUI

struct ContentView: View {
    //Property that enables saving data to the Managed Object Context. It holds the class that is generated by CoreData
    @Environment(\.managedObjectContext) private var moc
    //Read book from Core Data
    @FetchRequest(sortDescriptors: [
        //Sort by title than author
        SortDescriptor(\.title),
        SortDescriptor(\.author)
    ]) private var books: FetchedResults<Book>
    
    @State private var showingSheet: Bool = false
    
    var body: some View {
        NavigationView {
            List {
                ForEach(books) { book in
                    NavigationLink {
                        DetailView(book: book)
                    } label: {
                        HStack {
                            EmojiRatingView(rating: book.rating)
                                .font(.largeTitle)
                            VStack(alignment: .leading) {
                                Text(book.title ?? "Unknown")
                                    .font(.headline)
                                
                                Text(book.author  ?? "Unknown")
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                }
                .onDelete(perform: deleteBook)
            }
            .navigationTitle("Bookworm")
            .toolbar {
                ToolbarItem(placement: .navigationBarLeading) {
                    EditButton()
                }
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button {
                        showingSheet.toggle()
                    } label: {
                        Label("Add Book", systemImage: "plus")
                    }
                }
            }
        }
        .sheet(isPresented: $showingSheet) {
            AddBookView()
        }
    }
    
    func deleteBook(at offsets: IndexSet) {
        for offset in offsets {
            let book = books[offset]
            moc.delete(book)
        }
        
        try? moc.save()
    }
    
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
